language: go

os:
- linux
- osx
- windows

go:
- '1.13'

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/magefile/mage
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - go test ./... -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - '[ "$TRAVIS_OS_NAME" == "windows" ] || mage lint'
